### ISSUE TITLE
Batch processing to get the topology features

### ISSUE THREAD

**Issue by wengzehang** [c-hofer/torchph#25]
Hi, thank you so much for sharing this useful library! I am wondering how to use it for handling batch input. For example, when I want to calculate the vr persistence l1 features of a batch with "BxNx3", one simple way is to use your "vr_persistence_l1" function with a for loop, which will cost a lot of time (B times compared with 1 input). Do you have any suggestion for this scenario?

**Comment by c-hofer** [comment]
Currently you have to use the loop approach as batch processing is not supported. cheers c.
